### PR TITLE
feat: add opcode search actions in kbar component

### PR DESCRIPTION
**Pull request by SouravInsights**
The easiest way to add opcode navigation to the kbd component is by manually adding individual actions for each opcode in the `useActions` lib but obviously, it is a cumbersome task to do it manually. 

I'll soon think about the easiest way to achieve this.  

But here's a demo of the current working implementation:
https://user-images.githubusercontent.com/26466468/177504643-becf42d6-a903-49de-8e1d-683c9623b896.mp4

### CODE REVIEW

**Comment by dorlevi** [comment]
Yep, that is a bit tedious, we will stay tuned and thanks so much for contributing.

**Comment by SouravInsights** [comment]
Hey, @dorlevi 👋 

This implementation works but in a weird way. At the first render when you select the Search Opcodes options it doesn't work but if you forcefully try to rerender the component by making a random change in the `rootSearchAction` variable in the `useOpcodesActions.tsx` file, it works fine.

Let me know if it doesn't make sense.

**Comment by dorlevi** [comment]
hi @SouravInsights, checked the preview branch and can't get the search to work

**Comment by SouravInsights** [comment]
> hi @SouravInsights, checked the preview branch and can't get the search to work

Did you try making a random change in the `rootSearchAction` variable within `useOpcodesActions.tsx` file?

Here's a [demo video](https://share.cleanshot.com/1Fshg5) for your reference! 

Let me know if it still doesn't work. @dorlevi

**Comment by SouravInsights** [comment]
hey, @dorlevi did it work for you?

**Comment by dorlevi** [comment]
I haven't tried, I watched the video and believe it works if you do that but no user would do that! We are currently short on FE resources when we alleviate that we can fix and merge but we can't merge at the current state.

**Comment by SouravInsights** [comment]
Yeah yeah of course, no user would do that. I'll figure out why that is happening & put up a fix soon.

**Comment by peroket** [comment]
Since there was no update on this in a long while, I'm closing the PR, but we would be happy to get that change if you have some time :-)

**Pull request closed without merging**
